# try to get a tag for param.version
git:
  depth: 300
  
language: python

# doesn't mean much as we install miniconda
python:
  - "2.7"

#cache:
#  directories:
#    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      # python doesn't seem to work on osx images
      language: generic
      osx_image: xcode8.3

before_script:
  - git fetch --unshallow --tags # try some more to get a tag for param.version
  # copied from https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create --file environment.yml -n testenv
  - source activate testenv
  - python setup.py build_ext
  - conda env export

script:
  # some kind of tk/matplotlib problem on osx? not setting tkagg early enough?
  # https://stackoverflow.com/questions/32019556/matplotlib-crashing-tkinter-application/34109240#34109240
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      DISPLAY= ./topographica -t quick;
    else
      ./topographica -t quick;
    fi


