name: topographica
channels:
 - ioam
 - conda-forge
 - defaults

dependencies:
 - python=2.7
 - numpy
 - pillow
 - scipy
 - matplotlib
 - cython
 - tk
 - ipython
 - jupyter
 - notebook
 - holoviews
 - eigen
 - pip:
   - git+https://github.com/ioam/param.git
#   - git+https://github.com/ioam/paramtk.git
   - git+https://github.com/ioam/featuremapper.git
   - git+https://github.com/ioam/imagen.git
   - git+https://github.com/ioam/lancet.git

# to do:
# - reference_data
# - builder
# - nbpublisher
# - gmpy
