name: topographica
channels:
 - ioam
 - conda-forge
 - defaults

dependencies:
 - python=2.7
 - numpy
 - pillow
 - scipy
 - matplotlib
 - cython
 - tk
 - ipython
 - jupyter
 - notebook
# - eigen
 - gcc
 - pip:
   - gmpy==1.17
   - weave
