#!/usr/bin/env python
# Typical way to launch Topographica; simply extends module search
# path and processes command-line arguments
import  sys, external, topo

# Process the command-line arguments
from topo.misc.commandline import process_argv
process_argv(sys.argv[1:])
