


<H1>Papers using or about Topographica</H1>





<h2>Journal Articles</h2>
<!-- BEGIN BIBLIOGRAPHY references -->
<!--
    DO NOT MODIFY THIS BIBLIOGRAPHY BY HAND!  IT IS MAINTAINED AUTOMATICALLY!
    YOUR CHANGES WILL BE LOST THE NEXT TIME IT IS UPDATED!
--> 
<!-- Generated by: shared/bib2html/bib2html -b -min-crossrefs=9999 -r -c -d references bib2html.aux bib2html.tmp -->
<UL>

<!-- Authors: James A Bednar -->
<LI><A NAME="bednar:jpp12">James</A>&nbsp;A. Bednar.
<A HREF="http://dx.doi.org/10.1016/j.jphysparis.2011.12.001">Building a
  mechanistic model of the development and function of the primary visual
  cortex</A>.
<CITE>Journal of Physiology (Paris)</CITE>, 106:194-211, 2012.<P>

<!-- Authors: Alessio Plebe -->
<LI><A NAME="plebe:network12">Alessio</A> Plebe.
<A HREF="http://dx.doi.org/10.3109/0954898X.2012.690167">A model of the
  response of visual area V2 to combinations of orientations</A>.
<CITE>Network</CITE>, 23(3):105-122, 2012.<P>

<!-- Authors: Jan Antolik and James A Bednar -->
<LI><A NAME="antolik:fcn11">Jan</A> Antolik and
  James&nbsp;A. Bednar.
<A HREF="http://dx.doi.org/10.3389/fncom.2011.00017">Development of maps of
  simple and complex cells in the primary visual cortex</A>.
<CITE>Frontiers in Computational Neuroscience</CITE>, 5:17, 2011.<P>

<!-- Authors: Stuart P Wilson and Judith S Law and Ben Mitchinson and Tony J
  Prescott and James A Bednar -->
<LI><A NAME="wilson:plosone10">Stuart</A>&nbsp;P. Wilson,
  Judith&nbsp;S. Law, Ben Mitchinson, Tony&nbsp;J. Prescott, and James&nbsp;A. Bednar.
<A HREF="http://dx.doi.org/10.1371/journal.pone.0008778">Modeling the emergence
  of whisker direction maps in rat barrel cortex</A>.
<CITE>PLoS One</CITE>, 5(1):e8778, 2010.<P>

<!-- Authors: James A Bednar -->
<LI><A NAME="bednar:fin09">James</A>&nbsp;A. Bednar.
<A HREF="http://dx.doi.org/10.3389/neuro.11.008.2009">Topographica:
  Building and analyzing map-level simulations from Python, C/C++,
  MATLAB, NEST, or NEURON components</A>.
<CITE>Frontiers in Neuroinformatics</CITE>, 3:8, 2009.<P>

<!-- Authors: James A Bednar -->
<LI><A NAME="bednar:bmm08">James</A>&nbsp;A. Bednar.
<A HREF="http://www.brains-minds-media.org/archive/1402">Understanding neural
  maps with Topographica</A>.
<CITE>Brains, Minds, and Media</CITE>, 3:bmm1402, 2008.<P>

<!-- Authors: James A Bednar and Yoonsuck Choe and Judah De Paula and Risto
  Miikkulainen and Jefferson Provost and Tal Tversky -->
<LI><A NAME="bednar:neurocomputing04-sw">James</A>&nbsp;A.
  Bednar, Yoonsuck Choe, Judah De Paula, Risto Miikkulainen, Jefferson
  Provost, and Tal Tversky.
<A HREF="http://nn.cs.utexas.edu/keyword?bednar:neurocomputing04-sw">Modeling
  cortical maps with Topographica</A>.
<CITE>Neurocomputing</CITE>, pages 1129-1135, 2004.<P>

<!-- Authors: James A Bednar and Amol Kelkar and Risto Miikkulainen -->
<LI><A NAME="bednar:neuroinformatics04">James</A>&nbsp;A.
  Bednar, Amol Kelkar, and Risto Miikkulainen.
<A HREF="http://nn.cs.utexas.edu/keyword?bednar:neuroinformatics04">Scaling
  self-organizing maps to model large cortical networks</A>.
<CITE>Neuroinformatics</CITE>, 2:275-302, 2004.<P>

</UL>

<!-- END BIBLIOGRAPHY references -->






<h2>Book Chapters</h2>
<!-- BEGIN BIBLIOGRAPHY references -->
<!--
    DO NOT MODIFY THIS BIBLIOGRAPHY BY HAND!  IT IS MAINTAINED AUTOMATICALLY!
    YOUR CHANGES WILL BE LOST THE NEXT TIME IT IS UPDATED!
--> 
<!-- Generated by: shared/bib2html/bib2html -b -min-crossrefs=9999 -r -c -d references bib2html.aux bib2html.tmp -->
<UL>

<!-- Authors: James A Bednar -->
<LI><A NAME="bednar:ecn13">James</A>&nbsp;A. Bednar.
Topographica.
In Dieter Jaeger and Ranu Jung, editors, <CITE>The Encyclopedia of
  Computational Neuroscience</CITE>. Springer, 2013.
In preparation.<P>

<!-- Authors: James A Bednar -->
<LI><A NAME="bednar:devleann12">James</A>&nbsp;A. Bednar.
Constructing complex systems via activity-driven unsupervised Hebbian
  self-organization.
In <CITE>Growing Adaptive Machines: Combining Development and Learning in
  Artificial Neural Networks</CITE>, Studies in Computational Intelligence.
  Springer, Berlin, 2012.
In press.<P>

<!-- Authors: James A Bednar and Christopher E Ball -->
<LI><A NAME="bednar:scholarpedia12">James</A>&nbsp;A.
  Bednar and Christopher&nbsp;E. Ball.
Topographica.
In Eugene&nbsp;M. Izhikevich, editor, <CITE>The Encyclopedia of Computational
  Neuroscience</CITE>. <EM>Scholarpedia</EM>, 2012.
In preparation.<P>

</UL>

<!-- END BIBLIOGRAPHY references -->







<h2>Conference Papers</h2>
<!-- BEGIN BIBLIOGRAPHY references -->
<!--
    DO NOT MODIFY THIS BIBLIOGRAPHY BY HAND!  IT IS MAINTAINED AUTOMATICALLY!
    YOUR CHANGES WILL BE LOST THE NEXT TIME IT IS UPDATED!
--> 
<!-- Generated by: shared/bib2html/bib2html -b -min-crossrefs=9999 -r -c -d references bib2html.aux bib2html.tmp -->
<UL>

<!-- Authors: James A Bednar -->
<LI><A NAME="bednar:eccv12">James</A>&nbsp;A. Bednar.
Visual cortex as a general-purpose information-processing device.
In A.&nbsp;Fusiello et&nbsp;al., editors, <CITE>ECCV 2012 Workshops</CITE>, Part I,
  Lecture Notes in Computer Science 7583, pages 480-485, Berlin, 2012.
  Springer.
In press.<P>

<!-- Authors: Choonseog Park and Yoon H Bai and Yoonsuck Choe -->
<LI><A NAME="park:cimsvp09">Choonseog</A> Park, Yoon&nbsp;H.
  Bai, and Yoonsuck Choe.
<A HREF="http://faculty.cs.tamu.edu/choe/ftp/publications/park.cimsvp09.pdf">Tactile or visual?: Stimulus characteristics determine receptive field type in
  a self-organizing map model of cortical development</A>.
In <CITE>Proceedings of the 2009 IEEE Symposium on Computational Intelligence
  for Multimedia Signal and Vision Processing</CITE>, pages 6-13, 2009.
Best Student Paper Award.<P>

<!-- Authors: Choonseog Park and Heeyoul Choi and Yoonsuck Choe -->
<LI><A NAME="park:wsom09">Choonseog</A> Park, Heeyoul
  Choi, and Yoonsuck Choe.
<A HREF="http://faculty.cs.tamu.edu/choe/ftp/publications/park.wsom09.pdf">Tactile receptive fields: Exploring their textural origin and their
  representational properties</A>.
In <CITE>Advances in Self-Organizing Maps: Proceedings of the 7th International
  Workshop</CITE>, pages 228-236. Springer, 2009.<P>

<!-- Authors: Alessio Plebe and Vivian De la Cruz and Marco Mazzone -->
<LI><A NAME="plebe:icdl07">Alessio</A> Plebe, Vivian
  De la Cruz, and Marco Mazzone.
<A HREF="http://dx.doi.org/10.1109/DEVLRN.2007.4354050">Artificial learners of
  objects and names</A>.
In <CITE>Development and Learning, 2007. ICDL 2007. IEEE 6th
  International Conference on</CITE>, pages 300-305, 2007.<P>

</UL>

<!-- END BIBLIOGRAPHY references -->







<h2>PhD Theses</h2>
<!-- BEGIN BIBLIOGRAPHY references -->
<!--
    DO NOT MODIFY THIS BIBLIOGRAPHY BY HAND!  IT IS MAINTAINED AUTOMATICALLY!
    YOUR CHANGES WILL BE LOST THE NEXT TIME IT IS UPDATED!
--> 
<!-- Generated by: shared/bib2html/bib2html -b -min-crossrefs=9999 -r -c -d references bib2html.aux bib2html.tmp -->
<UL>

<!-- Authors: Stuart P Wilson -->
<LI><A NAME="wilson:phd11">Stuart</A>&nbsp;P. Wilson.
<A HREF="http://etheses.whiterose.ac.uk/2171/"><CITE>Figuring Time by Space:
  Representing Sensory Motion in Cortical Maps</CITE></A>.
PhD thesis, Department of Psychology, The University of Sheffield, Sheffield,
  UK, 2011.
Co-supervised with Tony J. Prescott.<P>

<!-- Authors: Chen Zhao -->
<LI><A NAME="zhao:phd11">Chen</A> Zhao.
<A HREF="http://hdl.handle.net/1842/5767"><CITE>Neural Mechanisms for Face and
  Orientation Aftereffects</CITE></A>.
PhD thesis, School of Informatics, The University of Edinburgh, Edinburgh, UK,
  2011.<P>

<!-- Authors: Jan Antolik -->
<LI><A NAME="antolik:phd10">Jan</A> Antolik.
<A HREF="http://hdl.handle.net/1842/4875"><CITE>Unified Developmental Model of
  Maps, Complex Cells and Surround Modulation in the Primary Visual
  Cortex</CITE></A>.
PhD thesis, School of Informatics, The University of Edinburgh, Edinburgh, UK,
  2010.<P>

<!-- Authors: Judith S Law -->
<LI><A NAME="law:phd09">Judith</A>&nbsp;S. Law.
<A HREF="http://hdl.handle.net/1842/3935"><CITE>Modeling the Development of
  Organization for Orientation Preference in Primary Visual Cortex</CITE></A>.
PhD thesis, School of Informatics, The University of Edinburgh, Edinburgh, UK,
  2009.<P>

<!-- Authors: Christopher M Palmer -->
<LI><A NAME="palmer:phd09">Christopher</A>&nbsp;M. Palmer.
<A HREF="http://hdl.handle.net/1842/4114"><CITE>Topographic and Laminar Models
  for the Development and Organisation of Spatial Frequency and Orientation in
  V1</CITE></A>.
PhD thesis, School of Informatics, The University of Edinburgh, Edinburgh, UK,
  2009.<P>

</UL>

<!-- END BIBLIOGRAPHY references -->







<h2>MSc Theses</h2>
<!-- BEGIN BIBLIOGRAPHY references -->
<!--
    DO NOT MODIFY THIS BIBLIOGRAPHY BY HAND!  IT IS MAINTAINED AUTOMATICALLY!
    YOUR CHANGES WILL BE LOST THE NEXT TIME IT IS UPDATED!
--> 
<!-- Generated by: shared/bib2html/bib2html -b -min-crossrefs=9999 -r -c -d references bib2html.aux bib2html.tmp -->
<UL>

<!-- Authors: Gautham Ganapathy -->
<LI><A NAME="ganapathy:ms11">Gautham</A> Ganapathy.
Reconciling models of visual cortex development with anatomical patterns of
  lateral connectivity.
Master's thesis, The University of Edinburgh, Scotland, UK, 2011.<P>

<!-- Authors: Bilal Khan -->
<LI><A NAME="khan:ms11">Bilal</A> Khan.
Modelling the pathway to auditory cortex.
Master's thesis, The University of Edinburgh, Scotland, UK, 2011.<P>

<!-- Authors: Konstantin Kudryavtsev -->
<LI><A NAME="kudryavtsev:ms11">Konstantin</A>
  Kudryavtsev.
High performance cortical simulator.
Master's thesis, The University of Edinburgh, Scotland, UK, 2011.<P>

<!-- Authors: Ravikiran Mattaparthi -->
<LI><A NAME="mattaparthi:ms11">Ravikiran</A>
  Mattaparthi.
User interface with real-world units.
Master's thesis, The University of Edinburgh, Scotland, UK, 2011.<P>

<!-- Authors: Jean Luc Stevens -->
<LI><A NAME="stevens:ms11">Jean</A>-Luc Stevens.
<A HREF="http://www.inf.ed.ac.uk/publications/thesis/online/IT111096.pdf">A
  temporal model of neural activity and VSD response in the primary visual
  cortex</A>.
Master's thesis, The University of Edinburgh, Scotland, UK, 2011.<P>

<!-- Authors: John Jacob -->
<LI><A NAME="jacob:ms09">John</A> Jacob.
Enhancing the performance of a cortical simulator by running it on a graphics
  processing unit.
Master's thesis, The University of Edinburgh, Scotland, UK, 2009.<P>

<!-- Authors: Kateryna Gerasymova -->
<LI><A NAME="gerasymova:ms08">Kateryna</A> Gerasymova.
Computational model of all known feature maps in the primary visual cortex.
Master's thesis, Humboldt-Universitaet zu Berlin, Germany, 2008.<P>

<!-- Authors: Stuart P Wilson -->
<LI><A NAME="wilson:ms07">Stuart</A>&nbsp;P. Wilson.
<A HREF="http://www.inf.ed.ac.uk/publications/thesis/online/IM070505.pdf">Self-organisation can explain the mapping of angular whisker deflections in the
  barrel cortex</A>.
Master's thesis, The University of Edinburgh, Scotland, UK, 2007.<P>

<!-- Authors: Veldri Kurniawan -->
<LI><A NAME="kurniawan:ms06">Veldri</A> Kurniawan.
<A HREF="http://www.inf.ed.ac.uk/publications/thesis/online/IM060401.pdf">Self-organizing visual cortex model using a homeostatic plasticity mechanism</A>.
Master's thesis, The University of Edinburgh, Scotland, UK, 2006.<P>

<!-- Authors: Chok Ming Ng -->
<LI><A NAME="ng:ms06">Chok</A>&nbsp;Ming Ng.
Topographica model of somatosensory cortex.
Master's thesis, The University of Edinburgh, Scotland, UK, 2006.<P>

<!-- Authors: Tikesh Ramtohul -->
<LI><A NAME="ramtohul:ms06">Tikesh</A> Ramtohul.
<A HREF="http://www.inf.ed.ac.uk/publications/thesis/online/IM060400.pdf">A
  self-organizing model of disparity maps in the primary visual cortex</A>.
Master's thesis, The University of Edinburgh, Scotland, UK, 2006.<P>

</UL>

<!-- END BIBLIOGRAPHY references -->


<P>Please send citations for any Topographica papers not listed above
to <A HREF="mailto:m4_jbednar_mail_address">Jim Bednar</A> so that
they can be included here.
