#!bin/python

__version__ = '$Revision: 9030 $'

import os
import sys
import re

def usage():
    print """
Usage: etc/update_095_to_096 [file] 

Example: etc/update_095_to_096 my_script.ty
"""

# Parse arguments
if len(sys.argv)!=2:
    usage()
    sys.exit(-1)


info = """
$Id$


This utility converts a script written for Topographica 0.9.5 into one
that will work with Topographica 0.9.6.

Your original script will not be altered; a new version will be saved
with the filename suffix '_0.9.6'.

If you find that the new version of your script will not run in
Topographica 0.9.6, you have three options:

(1) Submit your script to the Topographica developers via a support
    request on the web site, and we will try to improve this updating
    script to handle the problem

(2) Try to run the new script in Topographica with legacy support
    enabled by passing '-l' at startup
    (e.g. ./topographica -l -g your_script.ty)

(3) Update your script manually to match the new features of
    Topographica, e.g. by searching the ChangeLog.txt file to see what
    changes have been made since the previous release.
   
"""

print info

# should be ordered most to least specific
# CEBALERT: no need for separate list; can just use substitutions
substitutions = [
    # CEBALERT: still need to remove any imports of PipelineTF, etc
    ("output_fn\s*=\s*PipelineTF\(",""), # CEBALERT: these leave a trailing )
    ("output_fn\s*=\s*PipelineOF\(",""), #
    ("output_fn\s*=\s*Pipeline\(",""),   #
    ("output_fn\s*=\s*","output_fns=["), # CEBALERT: missing trailing ] 
    ]


replacements = [
    ('AttributeTrackingOF'           , 'AttributeTrackingTF'),
    ('ActivityAveragingOF'           , 'ActivityAveragingTF'),
    ('ScalingOF'                     , 'ScalingTF'),
    ('topo.outputfn'                 , 'topo.transferfn'),
    ('OutputFn'                      , 'TransferFn'),
    ('update_command'                , 'pre_plot_hooks'),
    ('plot_command'                  , 'plot_hooks'),
    ('before_pattern_presentation'   , 'pre_presentation_hooks'),
    ('after_pattern_presentation'    , 'post_presentation_hooks'),
    ('before_analysis_session'       , 'pre_analysis_session_hooks'),
    ('after_analysis_session'        , 'post_analysis_session_hooks'),
    ('apply_output_fn'               , 'apply_output_fns'),
    ('apply_output_fn_init'          , 'apply_output_fns_init')
    ]


# TO DO:
# .output_fn -> .output_fns[0]  or some kind of warning or leave it!

filename = sys.argv[1] 

s = open(filename,'r').read()

for old,new in substitutions:
    s = re.sub(old,new,s)

for old,new in replacements:
    s = new.join(s.split(old))

new_filename = filename+'_0.9.6'
open(new_filename,'w').write(s)

print "\n\nUpdating finished; output written to %s"%new_filename
